autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 50
  targetMemory: 50

updateStrategy:
  type: "RollingUpdate"

wordpressConfigureCache: true
memcached:
  enabled: true

wordpressUsername: "admin"
wordpressPassword: {{ .Values.secrets.wordpressPassword }}

mariadb:
  enabled: true
  auth:
    rootPassword: {{ .Values.secrets.mariadbRootPassword }}
    database: "bn_wordpress"
    username: "bn_wordpress"
    password: {{ .Values.secrets.mariadbPassword }}

secrets:
  wordpressPassword: ""
  mariadbPassword: ""
  mariadbRootPassword: ""
