autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 50
  targetMemory: 50
  
updateStrategy:
  type: "RollingUpdate"

wordpressConfigureCache: true
memcached:
  enabled: true
  
wordpressUsername: "admin"
wordpressPassword: null
existingSecret: "wordpress-secrets"
  
mariadb:
  enabled: true
  auth:
    existingSecret: "wordpress-secrets"
    rootPassword: null
    password: null
    database: "bn_wordpress"
    username: "bn_wordpress"